language: generic
sudo: true

services:
  - docker

env:
  matrix:
    - TAG=2.8
    - TAG=2.8-nordb
    - TAG=2.8-aof
    - TAG=3.0
    - TAG=3.0-nordb
    - TAG=3.0-aof
    - TAG=3.2
    - TAG=3.2-nordb
    - TAG=3.2-aof
    - TAG=4.0
    - TAG=4.0-nordb
    - TAG=4.0-aof
    - TAG=5.0
    - TAG=5.0-nordb
    - TAG=5.0-aof
    - TAG=6.0
    - TAG=6.0-nordb
    - TAG=6.0-aof
    - TAG=7.0
    - TAG=7.0-nordb
    - TAG=7.0-aof


script:
  - make build
  - make test

before_deploy:
  - export DOCKER_CONFIG="${HOME}/.docker"
  - mkdir -p "$DOCKER_CONFIG"
  - openssl aes-256-cbc -K $encrypted_a8d6dc0564c6_key -iv $encrypted_a8d6dc0564c6_iv -in .docker/config.json.enc -out "${DOCKER_CONFIG}/config.json" -d

deploy:
  provider: script
  skip_cleanup: true
  script: make push
  on:
    branch: master
