FROM quay.io/aptible/alpine:3.8

ENV REDIS_USER redis
RUN addgroup "$REDIS_USER"
RUN adduser -S "$REDIS_USER" -G "$REDIS_USER"

<% if ENV.fetch('REDIS_VERSION').to_f >= 6.0 %>
ENV VERSION_GTE_6=true
RUN apk-install ca-certificates sudo
<% if ENV.fetch('REDIS_VERSION').to_f >= 6.2 %>
ENV VERSION_GTE_6_2=true
<% end %>
<% else %>
RUN apk-install supervisor ca-certificates

ADD bin/install-stunnel.sh /install-stunnel.sh
RUN /install-stunnel.sh
<% end %>

ENV REDIS_VERSION <%= ENV.fetch 'REDIS_VERSION' %>
ENV REDIS_SHA1SUM <%= ENV.fetch 'REDIS_SHA1SUM' %>

ADD bin/install-redis.sh /install-redis.sh
RUN /install-redis.sh

# openssl is used to generate new certs if none are provided
# pwgen is used to generate password
RUN apk-install openssl pwgen

# rdbtools is used for importing an RDB dump remotely.
RUN apk-install py-pip coreutils && pip install rdbtools

ADD templates/redis.conf /etc/redis.conf

ADD bin/pick-free-port /usr/bin/
ADD bin/exit-event-listener /usr/bin/
ADD bin/redis-wrapper /usr/bin/

ADD bin/run-database.sh /usr/bin/
ADD bin/utilities.sh /usr/bin/

<% if ENV.fetch('REDIS_VERSION').to_f < 6.0 %>
ADD templates/supervisord.conf /etc/supervisord.conf

ADD bin/stunnel-wrapper /usr/bin/
ENV STUNNEL_ROOT_DIRECTORY=/etc/stunnel
<% end %>

# Default ENV
ENV DATA_DIRECTORY=/var/db CONFIG_DIRECTORY=/etc/redis
ENV SSL_CERTS_DIRECTORY=/etc/ssl/certs
ENV REDIS_PORT=6379 REDIS_PROTOCOL=redis
ENV SSL_PORT=6380 SSL_PROTOCOL=rediss

ENV CA_CERTS=/etc/ssl

<% if ENV['REDIS_NORDB'] %>
ENV REDIS_NORDB <%= ENV.fetch 'REDIS_NORDB' %>
<% end %>

<% if ENV['REDIS_AOF'] %>
ENV REDIS_AOF <%= ENV.fetch 'REDIS_AOF' %>
<% end %>

ENV TAG <%= ENV.fetch 'TAG' %>

# Volumes: Aptible will automatically mount these on an EBS device
VOLUME ["$DATA_DIRECTORY"]
VOLUME ["$CONFIG_DIRECTORY"]

# Create default directories
<% if ENV.fetch('REDIS_VERSION').to_f >= 6.0 %>
RUN mkdir -p "$DATA_DIRECTORY" "$CONFIG_DIRECTORY"
<% else %>
RUN mkdir -p "$DATA_DIRECTORY" "$CONFIG_DIRECTORY" "$STUNNEL_ROOT_DIRECTORY"
<% end %>

# Integration tests
ADD <%= ENV.fetch 'TAG' %>/test /tmp/test/<%= ENV.fetch 'TAG' %>
ADD test /tmp/test

EXPOSE 6379
EXPOSE 6380

ENTRYPOINT ["run-database.sh"]
